# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watermark_gui5.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.Centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Centralwidget.sizePolicy().hasHeightForWidth())
        self.Centralwidget.setSizePolicy(sizePolicy)
        self.Centralwidget.setObjectName("Centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.Centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(-10, 0, 441, 251))
        self.MainFrame.setAutoFillBackground(True)
        self.MainFrame.setObjectName("MainFrame")
        self.folderLabel = QtWidgets.QLabel(self.MainFrame)
        self.folderLabel.setGeometry(QtCore.QRect(20, 10, 206, 16))
        self.folderLabel.setObjectName("folderLabel")
        self.folderButton = QtWidgets.QPushButton(self.MainFrame)
        self.folderButton.setGeometry(QtCore.QRect(300, 10, 121, 23))
        self.folderButton.setObjectName("folderButton")
        self.folderPath = QtWidgets.QLineEdit(self.MainFrame)
        self.folderPath.setEnabled(True)
        self.folderPath.setGeometry(QtCore.QRect(20, 40, 401, 20))
        self.folderPath.setReadOnly(True)
        self.folderPath.setObjectName("folderPath")
        self.watermarkLabel = QtWidgets.QLabel(self.MainFrame)
        self.watermarkLabel.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.watermarkLabel.setObjectName("watermarkLabel")
        self.watermarkButton = QtWidgets.QPushButton(self.MainFrame)
        self.watermarkButton.setEnabled(True)
        self.watermarkButton.setGeometry(QtCore.QRect(300, 70, 121, 23))
        self.watermarkButton.setChecked(False)
        self.watermarkButton.setObjectName("watermarkButton")
        self.watermarkPath = QtWidgets.QLineEdit(self.MainFrame)
        self.watermarkPath.setGeometry(QtCore.QRect(20, 100, 401, 20))
        self.watermarkPath.setReadOnly(True)
        self.watermarkPath.setObjectName("watermarkPath")
        self.watermarkPositionLabel = QtWidgets.QLabel(self.MainFrame)
        self.watermarkPositionLabel.setGeometry(QtCore.QRect(20, 130, 191, 16))
        self.watermarkPositionLabel.setObjectName("watermarkPositionLabel")
        self.watermarkPosition = QtWidgets.QComboBox(self.MainFrame)
        self.watermarkPosition.setGeometry(QtCore.QRect(310, 130, 110, 20))
        self.watermarkPosition.setMinimumContentsLength(0)
        self.watermarkPosition.setIconSize(QtCore.QSize(16, 16))
        self.watermarkPosition.setObjectName("watermarkPosition")
        self.watermarkPosition.addItem("")
        self.watermarkPosition.addItem("")
        self.watermarkPosition.addItem("")
        self.watermarkPosition.addItem("")
        self.watermarkPosition.addItem("")
        self.horizontalLine = QtWidgets.QFrame(self.MainFrame)
        self.horizontalLine.setGeometry(QtCore.QRect(20, 150, 401, 31))
        self.horizontalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLine.setObjectName("horizontalLine")
        self.progressBar = QtWidgets.QProgressBar(self.MainFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 180, 401, 21))
        self.progressBar.setStyleSheet("border-radius: 0px;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.processingButton = QtWidgets.QPushButton(self.MainFrame)
        self.processingButton.setGeometry(QtCore.QRect(230, 210, 75, 23))
        self.processingButton.setObjectName("processingButton")
        self.openOutputFolderButton = QtWidgets.QPushButton(self.MainFrame)
        self.openOutputFolderButton.setGeometry(QtCore.QRect(320, 210, 101, 23))
        self.openOutputFolderButton.setObjectName("openOutputFolderButton")
        self.horizontalLine.raise_()
        self.folderLabel.raise_()
        self.folderButton.raise_()
        self.folderPath.raise_()
        self.watermarkLabel.raise_()
        self.watermarkButton.raise_()
        self.watermarkPath.raise_()
        self.watermarkPositionLabel.raise_()
        self.watermarkPosition.raise_()
        self.progressBar.raise_()
        self.processingButton.raise_()
        self.openOutputFolderButton.raise_()
        self.InfoFrame = QtWidgets.QFrame(self.Centralwidget)
        self.InfoFrame.setGeometry(QtCore.QRect(-10, -1, 441, 251))
        self.InfoFrame.setAutoFillBackground(True)
        self.InfoFrame.setObjectName("InfoFrame")
        self.infoImageLabel = QtWidgets.QLabel(self.InfoFrame)
        self.infoImageLabel.setGeometry(QtCore.QRect(30, 20, 101, 101))
        self.infoImageLabel.setPixmap(QtGui.QPixmap(":/newIcon/icon_info.png"))
        self.infoImageLabel.setScaledContents(True)
        self.infoImageLabel.setObjectName("infoImageLabel")
        self.infoBackButton = QtWidgets.QPushButton(self.InfoFrame)
        self.infoBackButton.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.infoBackButton.setObjectName("infoBackButton")
        self.infoDescriptionLabel = QtWidgets.QLabel(self.InfoFrame)
        self.infoDescriptionLabel.setGeometry(QtCore.QRect(150, 10, 281, 231))
        self.infoDescriptionLabel.setObjectName("infoDescriptionLabel")
        self.SettingsFrame = QtWidgets.QFrame(self.Centralwidget)
        self.SettingsFrame.setGeometry(QtCore.QRect(-10, 0, 441, 251))
        self.SettingsFrame.setAutoFillBackground(True)
        self.SettingsFrame.setObjectName("SettingsFrame")
        self.settDefaultsButton = QtWidgets.QPushButton(self.SettingsFrame)
        self.settDefaultsButton.setGeometry(QtCore.QRect(30, 210, 91, 23))
        self.settDefaultsButton.setObjectName("settDefaultsButton")
        self.settVerticalLine = QtWidgets.QFrame(self.SettingsFrame)
        self.settVerticalLine.setGeometry(QtCore.QRect(210, 10, 20, 181))
        self.settVerticalLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.settVerticalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.settVerticalLine.setObjectName("settVerticalLine")
        self.settDimensionsCheck = QtWidgets.QCheckBox(self.SettingsFrame)
        self.settDimensionsCheck.setGeometry(QtCore.QRect(20, 20, 191, 17))
        self.settDimensionsCheck.setObjectName("settDimensionsCheck")
        self.settFormatCheck = QtWidgets.QCheckBox(self.SettingsFrame)
        self.settFormatCheck.setGeometry(QtCore.QRect(240, 20, 161, 17))
        self.settFormatCheck.setObjectName("settFormatCheck")
        self.settHeightRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settHeightRadio.setEnabled(False)
        self.settHeightRadio.setGeometry(QtCore.QRect(40, 50, 151, 17))
        self.settHeightRadio.setObjectName("settHeightRadio")
        self.settWidthRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settWidthRadio.setEnabled(False)
        self.settWidthRadio.setGeometry(QtCore.QRect(40, 80, 141, 17))
        self.settWidthRadio.setObjectName("settWidthRadio")
        self.settJPEGRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settJPEGRadio.setEnabled(False)
        self.settJPEGRadio.setGeometry(QtCore.QRect(260, 50, 82, 17))
        self.settJPEGRadio.setObjectName("settJPEGRadio")
        self.settPNGRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settPNGRadio.setEnabled(False)
        self.settPNGRadio.setGeometry(QtCore.QRect(260, 80, 82, 17))
        self.settPNGRadio.setObjectName("settPNGRadio")
        self.settBMPRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settBMPRadio.setEnabled(False)
        self.settBMPRadio.setGeometry(QtCore.QRect(260, 110, 82, 17))
        self.settBMPRadio.setObjectName("settBMPRadio")
        self.settGIFRadio = QtWidgets.QRadioButton(self.SettingsFrame)
        self.settGIFRadio.setEnabled(False)
        self.settGIFRadio.setGeometry(QtCore.QRect(260, 140, 82, 17))
        self.settGIFRadio.setObjectName("settGIFRadio")
        self.settHorizontalLine = QtWidgets.QFrame(self.SettingsFrame)
        self.settHorizontalLine.setGeometry(QtCore.QRect(30, 190, 381, 16))
        self.settHorizontalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.settHorizontalLine.setObjectName("settHorizontalLine")
        self.settManualDimensionsCheck = QtWidgets.QCheckBox(self.SettingsFrame)
        self.settManualDimensionsCheck.setEnabled(False)
        self.settManualDimensionsCheck.setGeometry(QtCore.QRect(40, 110, 171, 17))
        self.settManualDimensionsCheck.setObjectName("settManualDimensionsCheck")
        self.settHeightLabel = QtWidgets.QLabel(self.SettingsFrame)
        self.settHeightLabel.setGeometry(QtCore.QRect(40, 140, 47, 13))
        self.settHeightLabel.setObjectName("settHeightLabel")
        self.settWidthLabel = QtWidgets.QLabel(self.SettingsFrame)
        self.settWidthLabel.setGeometry(QtCore.QRect(40, 170, 47, 13))
        self.settWidthLabel.setObjectName("settWidthLabel")
        self.settManualHeightEdit = QtWidgets.QLineEdit(self.SettingsFrame)
        self.settManualHeightEdit.setEnabled(False)
        self.settManualHeightEdit.setGeometry(QtCore.QRect(90, 140, 91, 20))
        self.settManualHeightEdit.setObjectName("settManualHeightEdit")
        self.settManualWidthEdit = QtWidgets.QLineEdit(self.SettingsFrame)
        self.settManualWidthEdit.setEnabled(False)
        self.settManualWidthEdit.setGeometry(QtCore.QRect(90, 170, 91, 20))
        self.settManualWidthEdit.setObjectName("settManualWidthEdit")
        self.settHeightPixLabel = QtWidgets.QLabel(self.SettingsFrame)
        self.settHeightPixLabel.setGeometry(QtCore.QRect(190, 140, 21, 16))
        self.settHeightPixLabel.setObjectName("settHeightPixLabel")
        self.settWidthPixLabel = QtWidgets.QLabel(self.SettingsFrame)
        self.settWidthPixLabel.setGeometry(QtCore.QRect(190, 170, 16, 16))
        self.settWidthPixLabel.setObjectName("settWidthPixLabel")
        self.settOkButton = QtWidgets.QPushButton(self.SettingsFrame)
        self.settOkButton.setGeometry(QtCore.QRect(340, 210, 75, 23))
        self.settOkButton.setObjectName("settOkButton")
        self.settWidthRadio.raise_()
        self.settDefaultsButton.raise_()
        self.settVerticalLine.raise_()
        self.settDimensionsCheck.raise_()
        self.settFormatCheck.raise_()
        self.settHeightRadio.raise_()
        self.settJPEGRadio.raise_()
        self.settPNGRadio.raise_()
        self.settBMPRadio.raise_()
        self.settGIFRadio.raise_()
        self.settHorizontalLine.raise_()
        self.settManualDimensionsCheck.raise_()
        self.settHeightLabel.raise_()
        self.settWidthLabel.raise_()
        self.settManualHeightEdit.raise_()
        self.settManualWidthEdit.raise_()
        self.settHeightPixLabel.raise_()
        self.settWidthPixLabel.raise_()
        self.settOkButton.raise_()
        self.MainFrame.raise_()
        self.SettingsFrame.raise_()
        self.InfoFrame.raise_()
        MainWindow.setCentralWidget(self.Centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 425, 21))
        self.menuBar.setObjectName("menuBar")
        self.settings = QtWidgets.QMenu(self.menuBar)
        self.settings.setMouseTracking(True)
        self.settings.setObjectName("settings")
        self.reference = QtWidgets.QMenu(self.menuBar)
        self.reference.setObjectName("reference")
        MainWindow.setMenuBar(self.menuBar)
        self.changeSettings = QtWidgets.QAction(MainWindow)
        self.changeSettings.setObjectName("changeSettings")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.settings.addAction(self.changeSettings)
        self.reference.addAction(self.about)
        self.menuBar.addAction(self.settings.menuAction())
        self.menuBar.addAction(self.reference.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watermark"))
        self.folderLabel.setText(_translate("MainWindow", "Выбрать папку с файлами изображений:"))
        self.folderButton.setText(_translate("MainWindow", "Выбрать"))
        self.watermarkLabel.setText(_translate("MainWindow", "Выбрать файл с водяным знаком:"))
        self.watermarkButton.setText(_translate("MainWindow", "Выбрать"))
        self.watermarkPositionLabel.setText(_translate("MainWindow", "Место установки водяного знака:"))
        self.watermarkPosition.setItemText(0, _translate("MainWindow", "Выбрать"))
        self.watermarkPosition.setItemText(1, _translate("MainWindow", "Левый верхний"))
        self.watermarkPosition.setItemText(2, _translate("MainWindow", "Левый нижний"))
        self.watermarkPosition.setItemText(3, _translate("MainWindow", "Правый верхний"))
        self.watermarkPosition.setItemText(4, _translate("MainWindow", "Правый нижний"))
        self.progressBar.setFormat(_translate("MainWindow", "%v/%m"))
        self.processingButton.setText(_translate("MainWindow", "Выполнить"))
        self.openOutputFolderButton.setText(_translate("MainWindow", "Открыть папку"))
        self.infoBackButton.setText(_translate("MainWindow", "Назад"))
        self.infoDescriptionLabel.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\">Watermark app </p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Версия: v1.0 </p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа предназначена для автоматизирован-</p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ного добавления водяных знаков на большое</p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> количество изображений.<br /></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Авторы: </p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Александр Марков, Виталий Бордачёв</p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:800;\"><br />WeRproggers 2019</p></body></html>"))
        self.settDefaultsButton.setText(_translate("MainWindow", "По умолчанию"))
        self.settDimensionsCheck.setText(_translate("MainWindow", "Подгонять размер изображений"))
        self.settFormatCheck.setText(_translate("MainWindow", "Выбрать выходной формат"))
        self.settHeightRadio.setText(_translate("MainWindow", "подгонять по высоте"))
        self.settWidthRadio.setText(_translate("MainWindow", "подгонять по ширине"))
        self.settJPEGRadio.setText(_translate("MainWindow", "jpeg"))
        self.settPNGRadio.setText(_translate("MainWindow", "png"))
        self.settBMPRadio.setText(_translate("MainWindow", "bmp"))
        self.settGIFRadio.setText(_translate("MainWindow", "gif"))
        self.settManualDimensionsCheck.setText(_translate("MainWindow", "Указать желаемый размер"))
        self.settHeightLabel.setText(_translate("MainWindow", "высота:"))
        self.settWidthLabel.setText(_translate("MainWindow", "ширина:"))
        self.settHeightPixLabel.setText(_translate("MainWindow", "px"))
        self.settWidthPixLabel.setText(_translate("MainWindow", "px"))
        self.settOkButton.setText(_translate("MainWindow", "Ок"))
        self.settings.setStatusTip(_translate("MainWindow", "Ожидание"))
        self.settings.setTitle(_translate("MainWindow", "Настройки"))
        self.reference.setStatusTip(_translate("MainWindow", "Ожидание"))
        self.reference.setTitle(_translate("MainWindow", "Справка"))
        self.changeSettings.setText(_translate("MainWindow", "Изменить настройки"))
        self.about.setText(_translate("MainWindow", "О программе..."))

import wm_res_rc
